services:
  client:
    build:
      context: client/
      dockerfile: dev.Dockerfile
    image: vidtube-client-dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules

  server:
    build:
      context: server/
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/app
      - server_go_mod_cache:/go/pkg/mod
    ports:

volumes:
  client_node_modules:
  server_go_mod_cache:
