services:
  server:
    build:
      context: server/
    network_mode: "service:aws"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: "8080"
      DB_URL: ${DB_URL}
      S3_ENDPOINT: http://localhost:4566
      SQS_ENDPOINT: http://localhost:4566

  client:
    build:
      context: client/
    ports:
      - "8000:80"
  db:
    image: postgres:15
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tj
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: vidtube
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro

  aws:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "./bin/localstack/:/etc/localstack/init/ready.d"
      - "localstack-data:/var/lib/localstack"

volumes:
  pgdata:
  localstack-data:
